services:
  sandbox:
    image: tugboatqa/node:lts
    expose: 5000
    default: true
    commands:
      init:
        - yarn global add serve
        - mkdir -p /etc/service/serve
        - echo "#!/bin/sh" > /etc/service/serve/run
        - echo "serve -s ${TUGBOAT_ROOT}/packages/sandbox/dist/public" >> /etc/service/serve/run
        - chmod +x /etc/service/serve/run
      build:
        - yarn install --frozen-lockfile
        - yarn workspace sandbox build
